# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(0, 'Пусто'), (1, 'ВКонтакте'), (2, 'Телеграм')], default=0)),
                ('body', models.TextField()),
                ('user_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
